Problem 4.2

In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

#Create Matrix
matrix1 = np.random.randint(-10, 11, size=(3, 3))
matrix2 = np.random.randint(-10, 11, size=(3, 3))
matrix3 = np.random.randint(-10, 11, size=(3, 3))

print("Matrix 1")
print(matrix1)
print("\nMatrix 2")
print(matrix2)
print("\nMatrix 3")
print(matrix3)

Matrix 1
[[-6  3 -6]
 [-4  8  2]
 [ 5 -3 -3]]

Matrix 2
[[-9  6  3]
 [ 2  8 -6]
 [-4  1  0]]

Matrix 3
[[  8  10  -5]
 [ -1   3 -10]
 [ -3  -1  -8]]


In [2]:
#Inverse matrix
inverse1 = np.linalg.inv(matrix1)
inverse2 = np.linalg.inv(matrix2)
inverse3 = np.linalg.inv(matrix3)

print("\nInverse of Matrix 1:")
print(inverse1)
print("\nInverse of Matrix 2:")
print(inverse2)
print("\nInverse of Matrix 3:")
print(inverse3)


Inverse of Matrix 1:
[[-0.067  0.1    0.2  ]
 [-0.007  0.178  0.133]
 [-0.104 -0.011 -0.133]]

Inverse of Matrix 2:
[[ 0.031  0.016 -0.312]
 [ 0.125  0.063 -0.25 ]
 [ 0.177 -0.078 -0.438]]

Inverse of Matrix 3:
[[ 0.333 -0.833  0.833]
 [-0.216  0.775 -0.833]
 [-0.098  0.216 -0.333]]


In [3]:
#Identity Matrix
print("\nIdentity Matrix 1")
print(np.abs(matrix1 @ inverse1))

print("\nIdentity Matrix 2")
print(np.abs(matrix2 @ inverse2))

print("\nIdentity Matrix 3")
print(np.abs(matrix3 @ inverse3))


Identity Matrix 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity Matrix 2
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity Matrix 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
